package com.asad.couponesController.enums;

public enum CheckClientRequestEnum {
//COMPANY
COMPANYNAMENOTFOUND,COMPANYPASSWORDNOTFOUND,COMPANYEMAILNOTFOUND, COMPANYISEMPTY,
//CUSTOMER
CUSTOMERNAMENOTFOUND,CUSTOMERPASSWORDNOTFOUND,CUSTOMERISEMPTY,
//COUPONS
COUPONTITLENOTFOUND,COUPONSTARTDATENOTFOUND,COUPONENDDATENOTFOUND,COUPONAMOUNTNOTFOUND,
COUPONMASSAGENOTFOUND,COUPONPRICENOTFOUND,COUPONIMAGENOTFOUND, COUPONTYPENOTFOUND,COUPONISEMPTY,
}
