package com.asad.couponesController.enums;

public enum CheckClientRequestEnum {
	
//log in
	LOGINREQUSTISEMPTY,LOGINUSERNAMEISEMPTY,LOGINPASSWORDISEMPTY,
//COMPANY
COMPANYNAMENOTFOUND,COMPANYPASSWORDNOTFOUND,COMPANYEMAILNOTFOUND, COMPANYISEMPTY,
//CUSTOMER
CUSTOMERNAMENOTFOUND,CUSTOMERPASSWORDNOTFOUND,CUSTOMERISEMPTY,
//COUPONS
COUPONTITLENOTFOUND,COUPONSTARTDATENOTFOUND,COUPONENDDATENOTFOUND,COUPONAMOUNTNOTFOUND,
COUPONMASSAGENOTFOUND,COUPONPRICENOTFOUND,COUPONIMAGENOTFOUND, COUPONTYPENOTFOUND,COUPONISEMPTY,COUPONLISTISEMPTY
}
