package com.asad.couponesController.enums;

public enum LogInEnum {
LOGINSUCCESS,LOGINFAILED,  NOTLOGEDIN
,USERIDISNOTVALID, ALREADYLOGINEDINIDCOMFIRMED, ALREADYLOGGEDINIDCOMFIRMED, ALREADYLOGGEDIN;
}
