package com.asad.couponesController.enums;

public enum ResponseMassageEnum {
THECOMPANYUPDATED,COMPANYNOTFOUND,COMPANYDELETED,CUSTUMBERDELETED, CUSTOMERNOTFOUND, THECUSTOMERUPDATED
,LOGOUTSUCCESS,LOGOUTFAILED
}
