package com.asad.couponesController.enums;

public enum ResponseMassageEnum {
THECOMPANYUPDATED,COMPANYNOTFOUND,COMPANYDELETED,CUSTUMERDELETED, CUSTOMERNOTFOUND, THECUSTOMERUPDATED
,LOGOUTSUCCESS,LOGOUTFAILED, COUPONNOTFOUND, THECOUPONUPDATED, COMPANYNAMEMOSTNOTCHANGE, COUPONISNOTYOURS,
COUPONSAREZEROFORTHISCOMPANY, SPESIFICCOUPONDATAISNOTVALID, COUPONLISTISEMPTY, 
CUSTOMERNAMEMOSTNOTCHANGE, COUPONPRICEMUSTNOTBENEGATIVE, COMPANYNAMEISUSED,
COMPANYCREATED, CUSTOMERCREATED, CUSTOMERNAMEISUSED, COUPONISCREATED, 
COUPONAMEISALREADYUSED, COUPONDELETED, COUPONTITLEMOSTNOTCHANGE, 
COUPONPURCHASED, CANNOTPURCHASECOUPONTWICE, THECOUPONISNOLONGERAVAILABLE, CUSTOMRORCOUPONDOSNOTEXIST, THECUSTOMERDOSENOTHAVECOUPONS
}
